server:
  port: 3050
spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:3000/eureka' #url for publishing microservers

